domain:
  url:  ${domain:https://test.wenzhuo4657.org}
  home:  ${domain.url}/md-web

github:
  client-id:  ${GITHUB_CLIENT_ID}
  client-secret:  ${GITHUB_CLIENT_SECRET}
  redirect-uri: ${domain.url}/api/oauth/callback/github

email:
  enable: true
  config:
    from: wenzhuo4657@gmail.com
    to: wenzhuo4657@gmail.com
    password: ${GMAIL_PASSWORD}


# 在一键脚本当中，通知器项目需要作为常用项目部署在同一个主机里，但是个人使用时，需要单独部署，具体来说，在脚本当中应提供变量指定，
# NotifierBot 配置
notifierbot:
  # NotifierBot API 基础 URL，可通过环境变量 NOTIFIERBOT_BASE_URL 覆盖
  base-url: ${NOTIFIERBOT_BASE_URL:http://localhost:8089}