domain:
  url:  http://localhost:8080
  home:  http://localhost:8080   # 访问打包在静态目录的前端
#  home:  http://localhost:5173   # 访问前端项目自行启动的地址  npm run dev

email:
  enable: true
  config:
    from: wenzhuo4657@gmail.com
    to: wenzhuo4657@gmail.com
    password: ${GMAIL_PASSWORD}

github:
  client-id:  ${GITHUB_CLIENT_ID}
  client-secret:  ${GITHUB_CLIENT_SECRET}
  redirect-uri: ${domain.url}/api/oauth/callback/github



